[package]
name = "ionio-illustrate"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["James (Fuzzy) Swift"]
license = "MIT"
description = "Mass spectra with annotations for typst."
exclude = ["/assets/*", "/gallery/*", "/manual.pdf", "/manual.typ"]
